---

# Le nom du groupe
all:
  # L'instruction pour indiquer qu'on va recenser les hôtes (= serveurs distants) du groupe
  hosts:
    # Un premier hôte, qu'on identifie par son FQDN
    # /!\ La machine qui va exécuter Ansible (= le contrôleur) doit pouvoir résoudre ce FQDN (soit via un serveur DNS, soit via une entrée dans son fichier '/etc/hosts')
    serveur.corp.thales:
      # Le nom de l'utilisateur qu'Ansible utilisera pour se connecter à ce serveur
      ansible_user: admin

    # Un second hôte, qu'on identifie par son IP
    192.168.1.11:
      ansible_user: ubuntu
      
    # Un troisième hôte, qu'on identifie par un nom fonctionnel
    NOM_DU_SERVEUR:
      # On renseigne alors la variable spéciale 'ansible_host' pour indiquer le nom technique (IP ou FQDN) pour contacter le serveur
      ansible_host: 192.168.1.12
      ansible_user: user

# Pour plus d'informations sur la construction des inventaires, se référer à la documentation officielle : https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
